// GENERATED by tools/mps_gen_rust.py — DO NOT EDIT BY HAND.
// 源：languages/biolang/languageModels/structure.mps（JetBrains MPS 语言模型）
// 手动优化：复制本文件为 ast.rs 后修改（内存规划：arena 索引、紧凑布局）。
// @generated
#![allow(dead_code, non_camel_case_types, non_snake_case)]

pub const CONCEPT_COUNT: usize = 43;

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum ConceptKind {
    Program,
    Declaration,
    ConstDeclaration,
    VarDeclaration,
    StreamSignature,
    StreamFork,
    ClassDeclaration,
    MethodDeclaration,
    Param,
    FieldDeclaration,
    NeedDeclaration,
    MethodAnnotation,
    StreamAnnotation,
    StatementList,
    Statement,
    PrintStatement,
    ExpressionStatement,
    IfStatement,
    WhileStatement,
    ForStatement,
    BreakStatement,
    ContinueStatement,
    ResStatement,
    RefStatement,
    Expression,
    IntLiteral,
    FloatLiteral,
    StringLiteral,
    CharLiteral,
    VarRef,
    CallExpr,
    BinaryOp,
    IncExpr,
    NewExpr,
    AllExpr,
    GetExpr,
    CauseExpr,
    IndexExpr,
    RefExpr,
    Type,
    BaseType,
    ArrayType,
    RefType,
}

impl ConceptKind {
    pub const fn id(self) -> u64 {
        match self {
            ConceptKind::Program => 1216773217294795866,
            ConceptKind::Declaration => 7386355364439873765,
            ConceptKind::ConstDeclaration => 1470609280262043481,
            ConceptKind::VarDeclaration => 1352366579789677555,
            ConceptKind::StreamSignature => 904086573394407105,
            ConceptKind::StreamFork => 8294974582761536635,
            ConceptKind::ClassDeclaration => 2922830819113091605,
            ConceptKind::MethodDeclaration => 8871072310827228693,
            ConceptKind::Param => 4166467450068317649,
            ConceptKind::FieldDeclaration => 5308463345086835995,
            ConceptKind::NeedDeclaration => 7456574470842911107,
            ConceptKind::MethodAnnotation => 1786587908856012160,
            ConceptKind::StreamAnnotation => 4467787151206513278,
            ConceptKind::StatementList => 5584915986708709954,
            ConceptKind::Statement => 3388474491432060587,
            ConceptKind::PrintStatement => 1863416870945978731,
            ConceptKind::ExpressionStatement => 1530489804865912849,
            ConceptKind::IfStatement => 7118461063061725781,
            ConceptKind::WhileStatement => 7829365671168874302,
            ConceptKind::ForStatement => 6623273901032457551,
            ConceptKind::BreakStatement => 1814855668389810781,
            ConceptKind::ContinueStatement => 767331265621341045,
            ConceptKind::ResStatement => 7409032518707179932,
            ConceptKind::RefStatement => 3165608724129934925,
            ConceptKind::Expression => 736061898820820492,
            ConceptKind::IntLiteral => 3364576287787004598,
            ConceptKind::FloatLiteral => 6379708567399531767,
            ConceptKind::StringLiteral => 3810139151939774156,
            ConceptKind::CharLiteral => 5866350810821856007,
            ConceptKind::VarRef => 53986548518530378,
            ConceptKind::CallExpr => 3690918373148533658,
            ConceptKind::BinaryOp => 5767026021297867998,
            ConceptKind::IncExpr => 589123971571323936,
            ConceptKind::NewExpr => 3194777023801693457,
            ConceptKind::AllExpr => 817839119078630209,
            ConceptKind::GetExpr => 7366600935544522322,
            ConceptKind::CauseExpr => 4610826432414143868,
            ConceptKind::IndexExpr => 8038463736624838759,
            ConceptKind::RefExpr => 1667371651475744004,
            ConceptKind::Type => 2882539631332051241,
            ConceptKind::BaseType => 4489500828230833246,
            ConceptKind::ArrayType => 633873695694864854,
            ConceptKind::RefType => 5241099853839826441,
        }
    }
    pub const fn name(self) -> &'static str {
        match self {
            ConceptKind::Program => "Program",
            ConceptKind::Declaration => "Declaration",
            ConceptKind::ConstDeclaration => "ConstDeclaration",
            ConceptKind::VarDeclaration => "VarDeclaration",
            ConceptKind::StreamSignature => "StreamSignature",
            ConceptKind::StreamFork => "StreamFork",
            ConceptKind::ClassDeclaration => "ClassDeclaration",
            ConceptKind::MethodDeclaration => "MethodDeclaration",
            ConceptKind::Param => "Param",
            ConceptKind::FieldDeclaration => "FieldDeclaration",
            ConceptKind::NeedDeclaration => "NeedDeclaration",
            ConceptKind::MethodAnnotation => "MethodAnnotation",
            ConceptKind::StreamAnnotation => "StreamAnnotation",
            ConceptKind::StatementList => "StatementList",
            ConceptKind::Statement => "Statement",
            ConceptKind::PrintStatement => "PrintStatement",
            ConceptKind::ExpressionStatement => "ExpressionStatement",
            ConceptKind::IfStatement => "IfStatement",
            ConceptKind::WhileStatement => "WhileStatement",
            ConceptKind::ForStatement => "ForStatement",
            ConceptKind::BreakStatement => "BreakStatement",
            ConceptKind::ContinueStatement => "ContinueStatement",
            ConceptKind::ResStatement => "ResStatement",
            ConceptKind::RefStatement => "RefStatement",
            ConceptKind::Expression => "Expression",
            ConceptKind::IntLiteral => "IntLiteral",
            ConceptKind::FloatLiteral => "FloatLiteral",
            ConceptKind::StringLiteral => "StringLiteral",
            ConceptKind::CharLiteral => "CharLiteral",
            ConceptKind::VarRef => "VarRef",
            ConceptKind::CallExpr => "CallExpr",
            ConceptKind::BinaryOp => "BinaryOp",
            ConceptKind::IncExpr => "IncExpr",
            ConceptKind::NewExpr => "NewExpr",
            ConceptKind::AllExpr => "AllExpr",
            ConceptKind::GetExpr => "GetExpr",
            ConceptKind::CauseExpr => "CauseExpr",
            ConceptKind::IndexExpr => "IndexExpr",
            ConceptKind::RefExpr => "RefExpr",
            ConceptKind::Type => "Type",
            ConceptKind::BaseType => "BaseType",
            ConceptKind::ArrayType => "ArrayType",
            ConceptKind::RefType => "RefType",
        }
    }
    pub const fn alias(self) -> &'static str {
        match self {
            ConceptKind::Program => "program",
            ConceptKind::Declaration => "",
            ConceptKind::ConstDeclaration => "const",
            ConceptKind::VarDeclaration => "var",
            ConceptKind::StreamSignature => "stream sig",
            ConceptKind::StreamFork => "fork",
            ConceptKind::ClassDeclaration => "class",
            ConceptKind::MethodDeclaration => "method",
            ConceptKind::Param => "param",
            ConceptKind::FieldDeclaration => "field",
            ConceptKind::NeedDeclaration => "need",
            ConceptKind::MethodAnnotation => "m-anno",
            ConceptKind::StreamAnnotation => "s-anno",
            ConceptKind::StatementList => "block",
            ConceptKind::Statement => "",
            ConceptKind::PrintStatement => "print",
            ConceptKind::ExpressionStatement => "expr",
            ConceptKind::IfStatement => "if",
            ConceptKind::WhileStatement => "while",
            ConceptKind::ForStatement => "for",
            ConceptKind::BreakStatement => "break",
            ConceptKind::ContinueStatement => "continue",
            ConceptKind::ResStatement => "res",
            ConceptKind::RefStatement => "ref",
            ConceptKind::Expression => "",
            ConceptKind::IntLiteral => "int",
            ConceptKind::FloatLiteral => "float",
            ConceptKind::StringLiteral => "str",
            ConceptKind::CharLiteral => "char",
            ConceptKind::VarRef => "var ref",
            ConceptKind::CallExpr => "call",
            ConceptKind::BinaryOp => "binop",
            ConceptKind::IncExpr => "inc",
            ConceptKind::NewExpr => "new",
            ConceptKind::AllExpr => "ALL",
            ConceptKind::GetExpr => "get",
            ConceptKind::CauseExpr => "cause",
            ConceptKind::IndexExpr => "index",
            ConceptKind::RefExpr => "ref",
            ConceptKind::Type => "",
            ConceptKind::BaseType => "base type",
            ConceptKind::ArrayType => "array",
            ConceptKind::RefType => "ref type",
        }
    }
    pub const fn parent(self) -> Option<ConceptKind> {
        match self {
            ConceptKind::Program => None,
            ConceptKind::Declaration => None,
            ConceptKind::ConstDeclaration => Some(ConceptKind::Declaration),
            ConceptKind::VarDeclaration => Some(ConceptKind::Declaration),
            ConceptKind::StreamSignature => Some(ConceptKind::Declaration),
            ConceptKind::StreamFork => Some(ConceptKind::Declaration),
            ConceptKind::ClassDeclaration => Some(ConceptKind::Declaration),
            ConceptKind::MethodDeclaration => Some(ConceptKind::Declaration),
            ConceptKind::Param => None,
            ConceptKind::FieldDeclaration => None,
            ConceptKind::NeedDeclaration => Some(ConceptKind::Declaration),
            ConceptKind::MethodAnnotation => None,
            ConceptKind::StreamAnnotation => None,
            ConceptKind::StatementList => None,
            ConceptKind::Statement => None,
            ConceptKind::PrintStatement => Some(ConceptKind::Statement),
            ConceptKind::ExpressionStatement => Some(ConceptKind::Statement),
            ConceptKind::IfStatement => Some(ConceptKind::Statement),
            ConceptKind::WhileStatement => Some(ConceptKind::Statement),
            ConceptKind::ForStatement => Some(ConceptKind::Statement),
            ConceptKind::BreakStatement => Some(ConceptKind::Statement),
            ConceptKind::ContinueStatement => Some(ConceptKind::Statement),
            ConceptKind::ResStatement => Some(ConceptKind::Statement),
            ConceptKind::RefStatement => Some(ConceptKind::Statement),
            ConceptKind::Expression => None,
            ConceptKind::IntLiteral => Some(ConceptKind::Expression),
            ConceptKind::FloatLiteral => Some(ConceptKind::Expression),
            ConceptKind::StringLiteral => Some(ConceptKind::Expression),
            ConceptKind::CharLiteral => Some(ConceptKind::Expression),
            ConceptKind::VarRef => Some(ConceptKind::Expression),
            ConceptKind::CallExpr => Some(ConceptKind::Expression),
            ConceptKind::BinaryOp => Some(ConceptKind::Expression),
            ConceptKind::IncExpr => Some(ConceptKind::Expression),
            ConceptKind::NewExpr => Some(ConceptKind::Expression),
            ConceptKind::AllExpr => Some(ConceptKind::Expression),
            ConceptKind::GetExpr => Some(ConceptKind::Expression),
            ConceptKind::CauseExpr => Some(ConceptKind::Expression),
            ConceptKind::IndexExpr => Some(ConceptKind::Expression),
            ConceptKind::RefExpr => Some(ConceptKind::Expression),
            ConceptKind::Type => None,
            ConceptKind::BaseType => Some(ConceptKind::Type),
            ConceptKind::ArrayType => Some(ConceptKind::Type),
            ConceptKind::RefType => Some(ConceptKind::Type),
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub struct Program {
    pub kind: String, // property
    pub declarations: Vec<Declaration>, // link -> Declaration (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct ConstDeclaration {
    pub r#type: Type, // link -> Type (fLJekj4/1)
    pub init: Option<Expression>, // link -> Expression (0..1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct VarDeclaration {
    pub r#type: Type, // link -> Type (fLJekj4/1)
    pub init: Option<Expression>, // link -> Expression (0..1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct StreamSignature {
    pub fields: Vec<Box<FieldDeclaration>>, // link -> FieldDeclaration (0..n)
    pub methods: Vec<Box<MethodDeclaration>>, // link -> MethodDeclaration (0..n)
    pub annotations: Vec<Box<StreamAnnotation>>, // link -> StreamAnnotation (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct StreamFork {
    pub sig: String, // property
    pub fields: Vec<Box<FieldDeclaration>>, // link -> FieldDeclaration (0..n)
    pub methods: Vec<Box<MethodDeclaration>>, // link -> MethodDeclaration (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct ClassDeclaration {
    pub fields: Vec<Box<FieldDeclaration>>, // link -> FieldDeclaration (0..n)
    pub methods: Vec<Box<MethodDeclaration>>, // link -> MethodDeclaration (0..n)
    pub annotations: Vec<Box<StreamAnnotation>>, // link -> StreamAnnotation (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct MethodDeclaration {
    pub r#type: Type, // link -> Type (fLJekj4/1)
    pub params: Vec<Box<Param>>, // link -> Param (0..n)
    pub body: Box<StatementList>, // link -> StatementList (fLJekj4/1)
    pub annotations: Vec<Box<MethodAnnotation>>, // link -> MethodAnnotation (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct Param {
    pub r#type: Type, // link -> Type (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct FieldDeclaration {
    pub r#type: Type, // link -> Type (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct NeedDeclaration {
    pub kind: String, // property
    pub subject: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct MethodAnnotation {
    pub kind: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct StreamAnnotation {
    pub kind: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct StatementList {
    pub statement: Vec<Statement>, // link -> Statement (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct PrintStatement {
    pub newline: String, // property
    pub args: Vec<Expression>, // link -> Expression (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct ExpressionStatement {
    pub expr: Expression, // link -> Expression (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct IfStatement {
    pub cond: Expression, // link -> Expression (fLJekj4/1)
    pub then: Box<StatementList>, // link -> StatementList (fLJekj4/1)
    pub r#else: Option<Box<StatementList>>, // link -> StatementList (0..1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct WhileStatement {
    pub cond: Expression, // link -> Expression (fLJekj4/1)
    pub body: Box<StatementList>, // link -> StatementList (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct ForStatement {
    pub init: Option<Statement>, // link -> Statement (0..1)
    pub cond: Option<Expression>, // link -> Expression (0..1)
    pub update: Option<Expression>, // link -> Expression (0..1)
    pub body: Box<StatementList>, // link -> StatementList (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct BreakStatement {
}

#[derive(Debug, Clone, PartialEq)]
pub struct ContinueStatement {
}

#[derive(Debug, Clone, PartialEq)]
pub struct ResStatement {
    pub values: Vec<Expression>, // link -> Expression (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct RefStatement {
    pub reason: Option<Expression>, // link -> Expression (0..1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct IntLiteral {
    pub value: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct FloatLiteral {
    pub value: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct StringLiteral {
    pub value: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct CharLiteral {
    pub value: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct VarRef {
    pub name: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct CallExpr {
    pub qual: String, // property
    pub method: String, // property
    pub args: Vec<Expression>, // link -> Expression (0..n)
}

#[derive(Debug, Clone, PartialEq)]
pub struct BinaryOp {
    pub op: String, // property
    pub left: Expression, // link -> Expression (fLJekj4/1)
    pub right: Expression, // link -> Expression (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct IncExpr {
    pub op: String, // property
    pub name: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct NewExpr {
    pub cls: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct AllExpr {
    pub expr: Expression, // link -> Expression (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct GetExpr {
    pub expr: Expression, // link -> Expression (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct CauseExpr {
    pub expr: Expression, // link -> Expression (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct IndexExpr {
    pub base: Expression, // link -> Expression (fLJekj4/1)
    pub index: Expression, // link -> Expression (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct RefExpr {
    pub target: Expression, // link -> Expression (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct BaseType {
    pub kind: String, // property
}

#[derive(Debug, Clone, PartialEq)]
pub struct ArrayType {
    pub elementType: Type, // link -> Type (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub struct RefType {
    pub perm: String, // property
    pub follow: String, // property
    pub base: Type, // link -> Type (fLJekj4/1)
}

#[derive(Debug, Clone, PartialEq)]
pub enum Declaration {
    ConstDeclaration(Box<ConstDeclaration>),
    VarDeclaration(Box<VarDeclaration>),
    StreamSignature(Box<StreamSignature>),
    StreamFork(Box<StreamFork>),
    ClassDeclaration(Box<ClassDeclaration>),
    MethodDeclaration(Box<MethodDeclaration>),
    NeedDeclaration(Box<NeedDeclaration>),
}

#[derive(Debug, Clone, PartialEq)]
pub enum Expression {
    IntLiteral(Box<IntLiteral>),
    FloatLiteral(Box<FloatLiteral>),
    StringLiteral(Box<StringLiteral>),
    CharLiteral(Box<CharLiteral>),
    VarRef(Box<VarRef>),
    CallExpr(Box<CallExpr>),
    BinaryOp(Box<BinaryOp>),
    IncExpr(Box<IncExpr>),
    NewExpr(Box<NewExpr>),
    AllExpr(Box<AllExpr>),
    GetExpr(Box<GetExpr>),
    CauseExpr(Box<CauseExpr>),
    IndexExpr(Box<IndexExpr>),
    RefExpr(Box<RefExpr>),
}

#[derive(Debug, Clone, PartialEq)]
pub enum Statement {
    PrintStatement(Box<PrintStatement>),
    ExpressionStatement(Box<ExpressionStatement>),
    IfStatement(Box<IfStatement>),
    WhileStatement(Box<WhileStatement>),
    ForStatement(Box<ForStatement>),
    BreakStatement(Box<BreakStatement>),
    ContinueStatement(Box<ContinueStatement>),
    ResStatement(Box<ResStatement>),
    RefStatement(Box<RefStatement>),
}

#[derive(Debug, Clone, PartialEq)]
pub enum Type {
    BaseType(Box<BaseType>),
    ArrayType(Box<ArrayType>),
    RefType(Box<RefType>),
}

