// GENERATED by tools/mps_gen_rust.py — DO NOT EDIT BY HAND.
// 概念注册表：MPS 语言模型中的全部概念（名称/别名/概念 id/父概念）。
// @generated
#![allow(dead_code)]

pub struct ConceptInfo {
    pub name: &'static str,
    pub alias: &'static str,
    pub id: u64,
    pub parent: Option<&'static str>,
}

pub const CONCEPTS: &[ConceptInfo] = &[
    ConceptInfo { name: "Program", alias: "program", id: 1216773217294795866, parent: None },
    ConceptInfo { name: "Declaration", alias: "", id: 7386355364439873765, parent: None },
    ConceptInfo { name: "ConstDeclaration", alias: "const", id: 1470609280262043481, parent: Some("Declaration") },
    ConceptInfo { name: "VarDeclaration", alias: "var", id: 1352366579789677555, parent: Some("Declaration") },
    ConceptInfo { name: "StreamSignature", alias: "stream sig", id: 904086573394407105, parent: Some("Declaration") },
    ConceptInfo { name: "StreamFork", alias: "fork", id: 8294974582761536635, parent: Some("Declaration") },
    ConceptInfo { name: "ClassDeclaration", alias: "class", id: 2922830819113091605, parent: Some("Declaration") },
    ConceptInfo { name: "MethodDeclaration", alias: "method", id: 8871072310827228693, parent: Some("Declaration") },
    ConceptInfo { name: "Param", alias: "param", id: 4166467450068317649, parent: None },
    ConceptInfo { name: "FieldDeclaration", alias: "field", id: 5308463345086835995, parent: None },
    ConceptInfo { name: "NeedDeclaration", alias: "need", id: 7456574470842911107, parent: Some("Declaration") },
    ConceptInfo { name: "MethodAnnotation", alias: "m-anno", id: 1786587908856012160, parent: None },
    ConceptInfo { name: "StreamAnnotation", alias: "s-anno", id: 4467787151206513278, parent: None },
    ConceptInfo { name: "StatementList", alias: "block", id: 5584915986708709954, parent: None },
    ConceptInfo { name: "Statement", alias: "", id: 3388474491432060587, parent: None },
    ConceptInfo { name: "PrintStatement", alias: "print", id: 1863416870945978731, parent: Some("Statement") },
    ConceptInfo { name: "ExpressionStatement", alias: "expr", id: 1530489804865912849, parent: Some("Statement") },
    ConceptInfo { name: "IfStatement", alias: "if", id: 7118461063061725781, parent: Some("Statement") },
    ConceptInfo { name: "WhileStatement", alias: "while", id: 7829365671168874302, parent: Some("Statement") },
    ConceptInfo { name: "ForStatement", alias: "for", id: 6623273901032457551, parent: Some("Statement") },
    ConceptInfo { name: "BreakStatement", alias: "break", id: 1814855668389810781, parent: Some("Statement") },
    ConceptInfo { name: "ContinueStatement", alias: "continue", id: 767331265621341045, parent: Some("Statement") },
    ConceptInfo { name: "ResStatement", alias: "res", id: 7409032518707179932, parent: Some("Statement") },
    ConceptInfo { name: "RefStatement", alias: "ref", id: 3165608724129934925, parent: Some("Statement") },
    ConceptInfo { name: "Expression", alias: "", id: 736061898820820492, parent: None },
    ConceptInfo { name: "IntLiteral", alias: "int", id: 3364576287787004598, parent: Some("Expression") },
    ConceptInfo { name: "FloatLiteral", alias: "float", id: 6379708567399531767, parent: Some("Expression") },
    ConceptInfo { name: "StringLiteral", alias: "str", id: 3810139151939774156, parent: Some("Expression") },
    ConceptInfo { name: "CharLiteral", alias: "char", id: 5866350810821856007, parent: Some("Expression") },
    ConceptInfo { name: "VarRef", alias: "var ref", id: 53986548518530378, parent: Some("Expression") },
    ConceptInfo { name: "CallExpr", alias: "call", id: 3690918373148533658, parent: Some("Expression") },
    ConceptInfo { name: "BinaryOp", alias: "binop", id: 5767026021297867998, parent: Some("Expression") },
    ConceptInfo { name: "IncExpr", alias: "inc", id: 589123971571323936, parent: Some("Expression") },
    ConceptInfo { name: "NewExpr", alias: "new", id: 3194777023801693457, parent: Some("Expression") },
    ConceptInfo { name: "AllExpr", alias: "ALL", id: 817839119078630209, parent: Some("Expression") },
    ConceptInfo { name: "GetExpr", alias: "get", id: 7366600935544522322, parent: Some("Expression") },
    ConceptInfo { name: "CauseExpr", alias: "cause", id: 4610826432414143868, parent: Some("Expression") },
    ConceptInfo { name: "IndexExpr", alias: "index", id: 8038463736624838759, parent: Some("Expression") },
    ConceptInfo { name: "RefExpr", alias: "ref", id: 1667371651475744004, parent: Some("Expression") },
    ConceptInfo { name: "Type", alias: "", id: 2882539631332051241, parent: None },
    ConceptInfo { name: "BaseType", alias: "base type", id: 4489500828230833246, parent: Some("Type") },
    ConceptInfo { name: "ArrayType", alias: "array", id: 633873695694864854, parent: Some("Type") },
    ConceptInfo { name: "RefType", alias: "ref type", id: 5241099853839826441, parent: Some("Type") },
];

pub fn find(name: &str) -> Option<&'static ConceptInfo> {
    CONCEPTS.iter().find(|c| c.name == name)
}
