[package]
name = "bbb-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "BioLang Rust 实现 CLI（Rust+LLVM 重写阶段 M1）"

[[bin]]
name = "bbb"
path = "src/main.rs"

[dependencies]
bbb-syntax = { path = "../bbb-syntax" }
bbb-core = { path = "../bbb-core" }
bbb-vm = { path = "../bbb-vm" }
bbb-llvm = { path = "../bbb-llvm" }
