#!/usr/bin/env python3
"""mps_gen_rust.py — MPS 语言模型 → Rust 代码生成器（v1）。

以 JetBrains MPS 语言工作台的语言定义（languages/biolang/languageModels/
structure.mps，43 个概念）为唯一事实源，生成 Rust 实现骨架：

  rust/crates/bio-syntax/src/ast_generated.rs   # AST 类型（struct/enum/ConceptKind）
  rust/crates/bio-syntax/src/concepts_generated.rs  # 概念注册表（id/alias/父级）

生成产物带 GENERATED 标记，禁止手改。手动优化流程：
1. 复制 ast_generated.rs → ast.rs
2. 在 ast.rs 上做内存规划改造（arena 索引、紧凑布局等）
3. 结构模型更新后重跑本脚本，diff 同步

用法：
  python3 tools/mps_gen_rust.py [structure.mps 路径]
"""

from __future__ import annotations

import os
import re
import sys
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_MODEL = os.path.join(ROOT, "languages", "biolang", "languageModels", "structure.mps")

# MPS XML 中的属性/子元素 role
P_NAME = "TrG5h"          # 概念/属性名
P_CONCEPT_ID = "EcuMT"    # 概念 id
P_ALIAS = "34LRSv"        # 概念别名（编辑器里敲的关键字）
P_ABSTRACT = "R5$K7"      # 抽象概念
P_EXTENDS = "1TJDcQ"      # 父概念引用
P_DATATYPE = "AX2Wp"      # 属性数据类型引用
A_DATATYPE = "AX2Wp"      # 属性数据类型引用 role
E_PROP = "1TJgyi"         # PropertyDeclaration
E_LINK = "1TJgyj"         # LinkDeclaration
E_CONCEPT = "1TIwiD"      # ConceptDeclaration
A_ROLE = "20kJfa"         # link role
A_CARD = "20lbJX"         # link 基数（fLJekj4/1、fLJekj5/0..1、fLJekj6/0..n）
A_TARGET = "20lvS9"       # link 目标概念
A_RESOLVE = "resolve"     # 引用解析名
A_VALUE = "value"         # 属性值

RUST_KEYWORDS = {"type", "match", "mod", "move", "ref", "loop", "fn", "impl",
                 "trait", "use", "where", "in", "as", "async", "await", "dyn",
                 "else", "if", "for", "while", "break", "continue", "return",
                 "struct", "enum", "let", "const", "static", "pub", "self",
                 "super", "crate", "mut", "unsafe", "extern", "union"}

CARD_ONE = "fLJekj4/1"
CARD_OPT = "fLJekj5/0..1"
CARD_MANY = "fLJekj6/0..n"
# 兼容性：实际文件里 0..n 是 fLJekj5（见 structure.mps 实际值），两者都接受
CARD_MANY_ALT = "fLJekj5/0..n"


def rust_field(role: str) -> str:
    if role in RUST_KEYWORDS:
        return f"r#{role}"
    return role


def _props_of(node: ET.Element) -> dict[str, str]:
    """读取 MPS 节点的 <property role value> 子元素。"""
    out: dict[str, str] = {}
    for child in node:
        tag = child.tag.split("}")[-1]
        if tag == "property" and "value" in child.attrib:
            out[child.attrib.get("role", "")] = child.attrib["value"]
    return out


def _refs_of(node: ET.Element) -> dict[str, str]:
    """读取 MPS 节点的 <ref role resolve> 子元素。"""
    out: dict[str, str] = {}
    for child in node:
        tag = child.tag.split("}")[-1]
        if tag == "ref":
            out[child.attrib.get("role", "")] = child.attrib.get("resolve", "")
    return out


class Concept:
    def __init__(self, node: ET.Element):
        p = _props_of(node)
        r = _refs_of(node)
        self.name = p.get(P_NAME, "?")
        self.concept_id = int(p.get(P_CONCEPT_ID, "0") or 0)
        self.alias = p.get(P_ALIAS, "")
        self.is_abstract = p.get(P_ABSTRACT) == "true"
        self.parent = None
        self.props: list[tuple[str, str]] = []   # (name, dataType)
        self.links: list[tuple[str, str, str]] = []  # (role, target, cardinality)
        for child in node:
            ctag = child.tag.split("}")[-1]
            if ctag != "node":
                continue
            concept = child.attrib.get("concept", "")
            cp, cr = _props_of(child), _refs_of(child)
            if concept == E_PROP:
                self.props.append((cp.get(P_NAME, "?"),
                                   cr.get(A_DATATYPE, "string")))
            elif concept == E_LINK:
                card = cp.get(A_CARD, CARD_ONE)
                if card == CARD_MANY_ALT:
                    card = CARD_MANY
                self.links.append((cp.get(A_ROLE, "?"),
                                   cr.get(A_TARGET, "?"),
                                   card))

    @property
    def rust_name(self) -> str:
        return self.name


def parse_model(path: str) -> list[Concept]:
    tree = ET.parse(path)
    root = tree.getroot()
    concepts: list[Concept] = []
    for node in root:
        tag = node.tag.split("}")[-1]
        if tag == "node" and node.attrib.get("concept") == E_CONCEPT:
            concepts.append(Concept(node))
    # 父概念解析（extends 引用 resolve 名）
    by_name = {c.name: c for c in concepts}
    for node in root:
        tag = node.tag.split("}")[-1]
        if not (tag == "node" and node.attrib.get("concept") == E_CONCEPT):
            continue
        name = _props_of(node).get(P_NAME)
        if name in by_name:
            parent = _refs_of(node).get(P_EXTENDS, "")
            if parent in by_name:
                by_name[name].parent = parent
    return concepts


def gen_ast(concepts: list[Concept]) -> str:
    by_name = {c.name: c for c in concepts}
    abstract = {c.name for c in concepts if c.is_abstract}
    lines: list[str] = []
    w = lines.append

    w("// GENERATED by tools/mps_gen_rust.py — DO NOT EDIT BY HAND.")
    w("// 源：languages/biolang/languageModels/structure.mps（JetBrains MPS 语言模型）")
    w("// 手动优化：复制本文件为 ast.rs 后修改（内存规划：arena 索引、紧凑布局）。")
    w("// @generated")
    w("#![allow(dead_code, non_camel_case_types)]")
    w("")
    w(f"pub const CONCEPT_COUNT: usize = {len(concepts)};")
    w("")
    w("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]")
    w("pub enum ConceptKind {")
    for c in concepts:
        w(f"    {c.rust_name},")
    w("}")
    w("")
    w("impl ConceptKind {")
    w("    pub const fn id(self) -> u64 {")
    w("        match self {")
    for c in concepts:
        w(f"            ConceptKind::{c.rust_name} => {c.concept_id},")
    w("        }")
    w("    }")
    w("    pub const fn name(self) -> &'static str {")
    w("        match self {")
    for c in concepts:
        w(f"            ConceptKind::{c.rust_name} => \"{c.name}\",")
    w("        }")
    w("    }")
    w("    pub const fn alias(self) -> &'static str {")
    w("        match self {")
    for c in concepts:
        alias = c.alias or ""
        w(f"            ConceptKind::{c.rust_name} => \"{alias}\",")
    w("        }")
    w("    }")
    w("    pub const fn parent(self) -> Option<ConceptKind> {")
    w("        match self {")
    for c in concepts:
        if c.parent:
            w(f"            ConceptKind::{c.rust_name} => Some(ConceptKind::{c.parent}),")
        else:
            w(f"            ConceptKind::{c.rust_name} => None,")
    w("        }")
    w("    }")
    w("}")
    w("")

    # structs（非抽象概念）
    for c in concepts:
        if c.is_abstract:
            continue
        w(f"#[derive(Debug, Clone, PartialEq)]")
        w(f"pub struct {c.rust_name} {{")
        for role, _dt in c.props:
            w(f"    pub {rust_field(role)}: String, // property")
        for role, target, card in c.links:
            ty = rust_link_type(target, card, by_name)
            note = {"1": "1", CARD_OPT: "0..1", CARD_MANY: "0..n"}.get(card, card)
            w(f"    pub {rust_field(role)}: {ty}, // link -> {target} ({note})")
        w("}")
        w("")

    # 抽象概念 → enum（含全部具体子类）
    for name in sorted(abstract):
        children = [c for c in concepts if c.parent == name]
        if not children:
            continue
        w(f"#[derive(Debug, Clone, PartialEq)]")
        w(f"pub enum {name} {{")
        for c in children:
            w(f"    {c.rust_name}(Box<{c.rust_name}>),")
        w("}")
        w("")

    return "\n".join(lines) + "\n"


def rust_link_type(target: str, card: str, by_name: dict[str, Concept]) -> str:
    inner = target if target in by_name and by_name[target].is_abstract else f"Box<{target}>"
    if card == CARD_ONE:
        return inner
    if card == CARD_OPT:
        return f"Option<{inner}>"
    if card == CARD_MANY:
        return f"Vec<{inner}>"
    return f"/* unknown cardinality {card} */ {inner}"


def gen_concepts(concepts: list[Concept]) -> str:
    lines: list[str] = []
    w = lines.append
    w("// GENERATED by tools/mps_gen_rust.py — DO NOT EDIT BY HAND.")
    w("// 概念注册表：MPS 语言模型中的全部概念（名称/别名/概念 id/父概念）。")
    w("// @generated")
    w("#![allow(dead_code)]")
    w("")
    w("pub struct ConceptInfo {")
    w("    pub name: &'static str,")
    w("    pub alias: &'static str,")
    w("    pub id: u64,")
    w("    pub parent: Option<&'static str>,")
    w("}")
    w("")
    w("pub const CONCEPTS: &[ConceptInfo] = &[")
    for c in concepts:
        parent = f"Some(\"{c.parent}\")" if c.parent else "None"
        w(f'    ConceptInfo {{ name: "{c.name}", alias: "{c.alias}", id: {c.concept_id}, parent: {parent} }},')
    w("];")
    w("")
    w("pub fn find(name: &str) -> Option<&'static ConceptInfo> {")
    w("    CONCEPTS.iter().find(|c| c.name == name)")
    w("}")
    return "\n".join(lines) + "\n"


def main() -> int:
    model = sys.argv[1] if len(sys.argv) > 1 else DEFAULT_MODEL
    concepts = parse_model(model)
    print(f"parsed {len(concepts)} concepts from {model}")

    out_ast = os.path.join(ROOT, "rust", "crates", "bio-syntax", "src", "ast_generated.rs")
    out_concepts = os.path.join(ROOT, "rust", "crates", "bio-syntax", "src", "concepts_generated.rs")
    os.makedirs(os.path.dirname(out_ast), exist_ok=True)
    for path, content in ((out_ast, gen_ast(concepts)), (out_concepts, gen_concepts(concepts))):
        with open(path, "w", encoding="utf-8") as f:
            f.write(content)
        print(f"wrote {path} ({len(content)} bytes)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
