#include "bio.h"
#include <stdlib.h>

/* ═══════════════ 编译器（bio -b）═══════════════
 * 本语言可以解释也可以编译。编译策略：源码嵌入 —— 生成一个含程序源码的 C 驱动
 * 文件，链接解释器运行时（libbio.a），产出自包含的原生可执行文件。
 * 运行时不再需要 bio，且 100% 保真（请求模型/对象流/线程等全部复用解释器）。
 */
#ifndef BIO_HOME
#define BIO_HOME "."
#endif

/* 把源码转义成 C 字符串字面量 */
static char *escape_cstr(const char *s) {
    size_t n = strlen(s);
    char *out = aalloc(n * 2 + 2);
    char *p = out;
    for (const char *q = s; *q; q++) {
        unsigned char c = (unsigned char)*q;
        if (c == '"') { *p++ = '\\'; *p++ = '"'; }
        else if (c == '\\') { *p++ = '\\'; *p++ = '\\'; }
        else if (c == '\n') { *p++ = '\\'; *p++ = 'n'; }
        else if (c == '\t') { *p++ = '\\'; *p++ = 't'; }
        else if (c == '\r') { *p++ = '\\'; *p++ = 'r'; }
        else *p++ = (char)c;
    }
    *p = 0;
    return out;
}

/* 返回 0 成功；否则 1 */
int compile_program(const char *src, const char *outpath) {
    /* 1. 先解析校验：程序必须能通过词法/语法分析 */
    int ntok, err = 0;
    Tok *toks = tokenize(src, &ntok);
    Decl *decls = parse_program_tokens(toks, ntok, &err);
    if (err) {
        fprintf(stderr, "compile error: program does not parse\n");
        return 1;
    }
    (void)decls;

    /* 2. 生成驱动 C 文件 */
    char *esc = escape_cstr(src);
    size_t tmplen = strlen(outpath) + 32;
    char *tmp = aalloc(tmplen);
    snprintf(tmp, tmplen, "%s.generated.c", outpath);
    FILE *f = fopen(tmp, "w");
    if (!f) { fprintf(stderr, "compile error: cannot write %s\n", tmp); return 1; }
    fprintf(f,
        "/* Generated by bio -b. Do not edit. */\n"
        "#include \"bio.h\"\n"
        "static const char *BIO_SOURCE =\n"
        "    \"%s\";\n"
        "int main(void) { run_source(BIO_SOURCE); return 0; }\n",
        esc);
    fclose(f);

    /* 3. 调用 gcc：直接编译解释器运行时源码（不依赖预建的 libbio.a） */
    char cmd[8192];
    snprintf(cmd, sizeof cmd,
        "gcc -O2 -I\"%s/src\" -o \"%s\" \"%s\" "
        "\"%s/src/arena.c\" \"%s/src/lexer.c\" \"%s/src/value.c\" "
        "\"%s/src/builtin.c\" \"%s/src/parser.c\" \"%s/src/interp.c\" "
        "\"%s/src/bts.c\" \"%s/src/compile.c\" \"%s/src/toml.c\" \"%s/src/project.c\" -lm",
        BIO_HOME, outpath, tmp,
        BIO_HOME, BIO_HOME, BIO_HOME,
        BIO_HOME, BIO_HOME, BIO_HOME,
        BIO_HOME, BIO_HOME, BIO_HOME, BIO_HOME);
    int rc = system(cmd);
    remove(tmp);
    if (rc != 0) {
        fprintf(stderr, "compile error: gcc failed (exit status %d)\n", rc);
        return 1;
    }
    return 0;
}
