#include "bio.h"
#include <stdlib.h>

/* ═══════════════ Compiler (bio -b) ═══════════════
 * This language can be interpreted as well as compiled. Compilation strategy:
 * source embedding — generate a C driver containing the program source, link
 * against the interpreter runtime (libbio.a), and produce a self-contained
 * native executable. At runtime it needs neither bio nor the source, and it is
 * 100% faithful (request model / object streams / threads all reuse the interpreter).
 */
#ifndef BIO_HOME
#define BIO_HOME "."
#endif

/* Escape the source into a C string literal */
static char *escape_cstr(const char *s) {
    size_t n = strlen(s);
    char *out = aalloc(n * 2 + 2);
    char *p = out;
    for (const char *q = s; *q; q++) {
        unsigned char c = (unsigned char)*q;
        if (c == '"') { *p++ = '\\'; *p++ = '"'; }
        else if (c == '\\') { *p++ = '\\'; *p++ = '\\'; }
        else if (c == '\n') { *p++ = '\\'; *p++ = 'n'; }
        else if (c == '\t') { *p++ = '\\'; *p++ = 't'; }
        else if (c == '\r') { *p++ = '\\'; *p++ = 'r'; }
        else *p++ = (char)c;
    }
    *p = 0;
    return out;
}

/* Return 0 on success, 1 on failure */
int compile_program(const char *src, const char *outpath) {
    /* 1. Parse-validate first: the program must pass lexing/parsing */
    int ntok, err = 0;
    Tok *toks = tokenize(src, &ntok);
    Decl *decls = parse_program_tokens(toks, ntok, &err);
    if (err) {
        fprintf(stderr, "compile error: program does not parse\n");
        return 1;
    }
    (void)decls;

    /* 2. Generate the driver C file */
    char *esc = escape_cstr(src);
    size_t tmplen = strlen(outpath) + 32;
    char *tmp = aalloc(tmplen);
    snprintf(tmp, tmplen, "%s.generated.c", outpath);
    FILE *f = fopen(tmp, "w");
    if (!f) { fprintf(stderr, "compile error: cannot write %s\n", tmp); return 1; }
    fprintf(f,
        "/* Generated by bio -b. Do not edit. */\n"
        "#include \"bio.h\"\n"
        "static const char *BIO_SOURCE =\n"
        "    \"%s\";\n"
        "int main(void) { run_source(BIO_SOURCE); return 0; }\n",
        esc);
    fclose(f);

    /* 3. Invoke gcc: compile the interpreter runtime sources directly (no prebuilt libbio.a dependency) */
    char cmd[8192];
    snprintf(cmd, sizeof cmd,
        "gcc -O2 -I\"%s/src\" -o \"%s\" \"%s\" "
        "\"%s/src/arena.c\" \"%s/src/lexer.c\" \"%s/src/value.c\" "
        "\"%s/src/builtin.c\" \"%s/src/parser.c\" \"%s/src/interp.c\" "
        "\"%s/src/bts.c\" \"%s/src/compile.c\" \"%s/src/toml.c\" \"%s/src/project.c\" -lm",
        BIO_HOME, outpath, tmp,
        BIO_HOME, BIO_HOME, BIO_HOME,
        BIO_HOME, BIO_HOME, BIO_HOME,
        BIO_HOME, BIO_HOME, BIO_HOME, BIO_HOME);
    int rc = system(cmd);
    remove(tmp);
    if (rc != 0) {
        fprintf(stderr, "compile error: gcc failed (exit status %d)\n", rc);
        return 1;
    }
    return 0;
}
