#include "bio.h"
#include "platform.h"
#include <stdlib.h>

/* ═══════════════ Compiler (bio shell build) ═══════════════
 * This language can be interpreted as well as compiled. Compilation strategy:
 * source embedding — generate a C driver containing the program source, link
 * against the interpreter runtime, and produce a self-contained native
 * executable. At runtime it needs neither bio nor the source, and it is 100%
 * faithful (request model / object streams / threads all reuse the interpreter).
 */
#ifndef BIO_HOME
#define BIO_HOME "."
#endif
#ifndef BIO_CC
#define BIO_CC "gcc"
#endif
#ifndef BIO_LDFLAGS
#define BIO_LDFLAGS "-lm"
#endif

/* Escape the source into a C string literal */
static char *escape_cstr(const char *s) {
    size_t n = strlen(s);
    char *out = aalloc(n * 2 + 2);
    char *p = out;
    for (const char *q = s; *q; q++) {
        unsigned char c = (unsigned char)*q;
        if (c == '"') { *p++ = '\\'; *p++ = '"'; }
        else if (c == '\\') { *p++ = '\\'; *p++ = '\\'; }
        else if (c == '\n') { *p++ = '\\'; *p++ = 'n'; }
        else if (c == '\t') { *p++ = '\\'; *p++ = 't'; }
        else if (c == '\r') { *p++ = '\\'; *p++ = 'r'; }
        else *p++ = (char)c;
    }
    *p = 0;
    return out;
}

/* Split a string on whitespace into an argv array (points into s; NULL-terminated). */
static int split_args(const char *s, const char **argv, int cap) {
    int n = 0;
    while (*s) {
        while (*s && isspace((unsigned char)*s)) s++;
        if (!*s) break;
        if (n >= cap) break;
        argv[n++] = s;
        while (*s && !isspace((unsigned char)*s)) s++;
    }
    argv[n] = NULL;
    return n;
}

/* Build the gcc argv for BIO_CC's -I flag (paths may contain spaces). */
static void make_inc(const char *home, char *buf, size_t cap) {
    snprintf(buf, cap, "%s/src", home);
}

/* Return 0 on success, 1 on failure */
int compile_program(const char *src, const char *outpath) {
    /* 1. Parse-validate first: the program must pass lexing/parsing */
    int ntok, err = 0;
    Tok *toks = tokenize(src, &ntok);
    Decl *decls = parse_program_tokens(toks, ntok, &err);
    if (err) {
        fprintf(stderr, "compile error: program does not parse\n");
        return 1;
    }
    (void)decls;

    /* 2. Generate the driver C file */
    char *esc = escape_cstr(src);
    size_t tmplen = strlen(outpath) + 32;
    char *tmp = aalloc(tmplen);
    snprintf(tmp, tmplen, "%s.generated.c", outpath);
    FILE *f = fopen(tmp, "w");
    if (!f) { fprintf(stderr, "compile error: cannot write %s\n", tmp); return 1; }
    fprintf(f,
        "/* Generated by bio shell build. Do not edit. */\n"
        "#include <stdlib.h>\n"
        "#include \"bio.h\"\n"
        "static const char *BIO_SOURCE =\n"
        "    \"%s\";\n"
        "int main(void) {\n"
        "    const char *ml = getenv(\"BIO_MEM_LIMIT\");\n"
        "    bio_set_mem_limit(ml && *ml ? (size_t)strtoull(ml, 0, 0) : 0);\n"
        "    run_source(BIO_SOURCE);\n"
        "    return 0;\n"
        "}\n",
        esc);
    fclose(f);

    /* 3. Spawn the compiler directly (argv array — no shell, no quoting bugs).
     * Reuses the profile's compiler and link flags baked in at build time. */
    static const char *RUNTIME[] = {
        "arena.c", "lexer.c", "value.c", "builtin.c", "parser.c",
        "interp.c", "bts.c", "compile.c", "toml.c", "project.c", "platform.c"
    };
    const char **av = aalloc(sizeof(char *) * (2 + 1 + 2 + 2 + (int)(sizeof RUNTIME / sizeof *RUNTIME) + 1 + 8));
    int n = 0;
    av[n++] = BIO_CC;
    av[n++] = "-O2";
    char inc[BIO_PATH_MAX];
    make_inc(BIO_HOME, inc, sizeof inc);
    av[n++] = "-I";
    av[n++] = inc;
    av[n++] = "-o";
    av[n++] = outpath;
    av[n++] = tmp;
    for (size_t i = 0; i < sizeof RUNTIME / sizeof *RUNTIME; i++) {
        char *rp = aalloc(strlen(BIO_HOME) + strlen(RUNTIME[i]) + 8);
        snprintf(rp, strlen(BIO_HOME) + strlen(RUNTIME[i]) + 8, "%s/src/%s", BIO_HOME, RUNTIME[i]);
        av[n++] = rp;
    }
    const char *ld[8];
    int nld = split_args(BIO_LDFLAGS, ld, 8);
    for (int i = 0; i < nld; i++) av[n++] = ld[i];
    av[n] = NULL;

    int rc = bio_run(av);
    remove(tmp);
    if (rc != 0) {
        fprintf(stderr, "compile error: %s failed (exit status %d)\n", BIO_CC, rc);
        return 1;
    }
    return 0;
}
